services:
  - type: web
    name: ai-chatbot-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: CHROMA_PATH
        value: ./chroma_data
      - key: UPLOAD_DIR
        value: ./uploads
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: TOP_K
        value: "5"
      - key: CHUNK_SIZE
        value: "700"
      - key: CHUNK_OVERLAP
        value: "120"
      - key: PROJECT_NAME
        value: AI Document Chatbot
      - key: API_V1_STR
        value: /api

  - type: web
    name: ai-chatbot-frontend
    runtime: static
    buildCommand: npm --prefix frontend ci && npm --prefix frontend run build
    staticPublishPath: ./frontend/dist
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
